logging.level.org.springframework.web=DEBUG;

spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://db.cwiztech.com:3319/transport?autoReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=ALLAH@786

# Specify the DBMS
spring.jpa.database = MYSQL

# Show or not log for each sql query
spring.jpa.show-sql = true

database_type = MYSQL

# Hibernate settings are prefixed with spring.jpa.hibernate.*
# spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.naming_strategy = org.hibernate.cfg.ImprovedNamingStrategy

file_path.oauthapplicationPath=http://api.cwiztech.com:8080/
file_path.apiRequestLogPath=http://api.cwiztech.com:8002/

file_path.servicePath=cwiztech
file_path.commonServicePath=cwiztech

file_path.isLive=false

file_path.documents=C://xampp/htdocs/documents